baseURL = "https://ningfeiyu.github.io/"
languageCode = "zh-cn"
title = "Ningfeiyu"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowPostNavLinks = true

[params.profileMode]
enabled = false

[params.homeInfoParams]
Title = "NFY"
Content = "Nurture Flourish Yielding"

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 40

[[params.socialIcons]]
name = "email"
url = "mailto:root@ningop.com"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/ninfeo"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ningfeiyu"
