baseURL = "https://ningfeiyu.github.io/"
languageCode = "zh-cn"
title = "Ningfeiyu"
theme = "PaperMod"

[params]
defaultTheme = "auto"

[params.profileMode]
enabled = true
title = "Ningfeiyu"
subtitle = "Nurture Flourish Yielding"
